import type { Metadata } from "next";
import { Kanchenjunga } from "next/font/google";
import "./globals.css";
import { Providers } from "./providers";
import { TooltipProvider } from "@/components/ui/tooltip";
import {Toaster} from "@/components/ui/sonner";


const kanchenjunga = Kanchenjunga({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
  variable: "--font-kanchenjunga",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${kanchenjunga.className} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
         <Providers>
          <Toaster />
          <TooltipProvider>
                {children}
          </TooltipProvider>
        </Providers>
      </body>
    </html>
  );
}
