import type { Metadata } from "next";
import { Kanchenjunga } from "next/font/google";
import "./globals.css";
import { Providers } from "./providers";
import { Toaster } from "sonner";

const kanchenjunga = Kanchenjunga({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
  variable: "--font-kanchenjunga",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${kanchenjunga.className} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col"> <Providers>{children}<Toaster /> </Providers></body>
    </html>
  );
}
